---
version: build-{build}
skip_non_tags: true
environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    BITS: 64
  - TARGET: i686-pc-windows-msvc
    BITS: 32
  - TARGET: x86_64-pc-windows-gnu
    BITS: 64
  - TARGET: i686-pc-windows-gnu
    BITS: 32
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe" -FileName "rust-nightly.exe"
  - rust-nightly.exe /VERYSILENT /NORESTART /DIR="C:\rust"
  - ps: $env:PATH="$env:PATH;C:\rust\bin"
  - ps: $env:PATH="$env:PATH;C:\MinGW\bin"
  - rustc -V
  - cargo -V
build: off
test_script:
  # - cargo test --verbose // currently does not work on windows
  # Let's just check, if the binary can be executed at all.
  # - cargo run -- --help // Also doesn't work, because process "never" ends.
  # Let's just compile :(
  - cargo build --release
